### ISSUE TITLE
useTable

### ISSUE THREAD

**Issue by cdedreuille** [gbibeaul/use-supabase#1]
Hello 👋

Thanks a lot for starting of this project. This will be super useful. One thing I believe will be super useful would be to add realtime as part of the hook to listen to changes made in your query. I'm not entirely sure what's the best way to do this but adding an options object in the hook like `{realtime: true, type: 'INSERT'}` would be absolutely amazing.

```
useEffect(() => {
  // Listen for updates
  if (listener) {
    const listen = supabase
      .from(listener)
      .on('*', (payload) => console.log(payload)) // -> Do something here
      .subscribe();

    return () => {
      listen.unsubscribe();
    };
  }
  return () => {};
}, []);
```

Here is the realtime doc as a reference: https://supabase.io/docs/client/subscribe

**Comment by gbibeaul** [comment]
Ah I think I see what you mean. Here is a proposal I can try working on:

- hook would take as an argument both the supabase query and the callback
- hook would return something like `{ data, loading, error}` to build some optimistic UIs

**Comment by cdedreuille** [comment]
That sounds amazing and it would be so useful.

**Comment by gbibeaul** [comment]
Working on this tonight by the way

**Comment by gbibeaul** [comment]
@cdedreuille passing a call back felt like adding abstraction where it was not really needed. So Instead I came up with a hook to receive live all the data in a table. see t[his tweet for a demo](https://twitter.com/BibeauGuillaume/status/1366934713559117829). I still need to work on it but I should progress in the next few days.

**Comment by cdedreuille** [comment]
Ah cool. If I can help le me know.

**Comment by cdedreuille** [comment]
Sounds great. Can't wait to try it out.

**Comment by cdedreuille** [comment]
Hi, @gbibeaul 👋 Did you get a chance to work a bit more on `useTable`? I would be happy to help but I believe you didn't create any PR just yet.

**Comment by gbibeaul** [comment]
@cdedreuille yes I have a working version and I can open the PR. I am trying to make it memoized and global to allow some cross component sharing the live updates. 

The usage should not change much so i'll open the PR today but under the hood i'm exploring using it dynamically created reducers. 

I'll open the PR to get your impression and see how we can improve this

**Comment by cdedreuille** [comment]
Any update on when you are looking to release useTable?

**Comment by gbibeaul** [comment]
After a long long time! we have a useTable! released in v2
