### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by eunjae-lee** [gbibeaul/use-supabase#4]
Hi there, thanks for the useful hook.
I'm not sure if my issue regarding the auth is related to this hook or it needs to be escalated to supabase. Let me know!

So, I wrote these two hooks.

```js
function useRedirectToDashboard() {
  const { auth } = useSupabase();
  const router = useRouter();
  useEffect(() => {
    if (auth.user()) {
      router.push("/projects");
    }
  }, [auth]);
}

function useSecure() {
  const router = useRouter();
  const { auth } = useSupabase();
  useEffect(() => {
    if (!auth.user()) {
      router.push("/sign_in");
    }
  }, [auth]);
}
```

As the names imply, I use `useSecure` at the beginning of pages that require login. I use `useRedirectToDashboard` at `/sign_in` page, so that when a user is already signed in, then so that they can be redirected to the dashboard.

I'm having two issues:

1. After a certain amount of time, I get back to my website, and I guess the session is expired. And `useSecure` doesn't work. It still has `auth.user()` so it won't redirect to /sign_in page. However, please correct me if I'm wrong, isn't it something I should refresh the token and keep the session alive instead of sending the user to the sign in page? I'm not so knowledgeable on this topic.

2. In many cases, when (1) happens, I'm redirected to sign-in page and immediately get redirected back to the dashboard. It means, in that second, auth.user() was falsey and now truthy again.

Thanks for reading!

**Comment by gbibeaul** [comment]
Hi @eunjae-lee thanks for the issue!

can you provide a little but more information on your issue:
- framework
- which library does useRouter come from?

If possible can you please give a link to a repo or send a zip file to help reproduce?

**Comment by sk0le** [comment]
> Hi @eunjae-lee thanks for the issue!
> 
> can you provide a little but more information on your issue:
> 
> * framework
> * which library does useRouter come from?
> 
> If possible can you please give a link to a repo or send a zip file to help reproduce?

I'm assuming this useRouter comes from NextJS, you can read it here https://nextjs.org/docs/api-reference/next/router

**Comment by gbibeaul** [comment]
I will close this as it is inactive

**Comment by eunjae-lee** [comment]
Sorry I was busy and off for a while. I'll come back if I get more information.
